{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMTI4SYG0H05lKwnTGy21YT",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Dubakrishnamohan/drug-likeness-code/blob/krishna/Untitled2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "pip install rdkit\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "K5AySFL9ADj8",
        "outputId": "85502c94-cd80-415c-f8b5-7f221252f451"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting rdkit\n",
            "  Downloading rdkit-2025.9.6-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)\n",
            "Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)\n",
            "Downloading rdkit-2025.9.6-cp312-cp312-manylinux_2_28_x86_64.whl (36.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m36.7/36.7 MB\u001b[0m \u001b[31m43.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: rdkit\n",
            "Successfully installed rdkit-2025.9.6\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "from google.colab import files\n",
        "uploaded=files.upload()\n",
        "df=pd.read_csv(\"PubChem_compound_CID__ouUHalf9MkEFb7p2OA7zUWjn94dDA2X8H9l-sATIbLEE0VA.csv\")\n",
        "print(df)"
      ],
      "metadata": {
        "id": "RnhaQrBlD2jy",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "714bd294-ee95-499a-8956-f918943d0f04"
      },
      "execution_count": 31,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-331f2ab3-b149-4976-90d9-44475514d2db\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-331f2ab3-b149-4976-90d9-44475514d2db\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving PubChem_compound_CID__ouUHalf9MkEFb7p2OA7zUWjn94dDA2X8H9l-sATIbLEE0VA.csv to PubChem_compound_CID__ouUHalf9MkEFb7p2OA7zUWjn94dDA2X8H9l-sATIbLEE0VA (5).csv\n",
            "     Compound_CID                   Name  \\\n",
            "0             135  4-Hydroxybenzoic Acid   \n",
            "1             338         Salicylic Acid   \n",
            "2            1983          Acetaminophen   \n",
            "3            2244                Aspirin   \n",
            "4            4064            Meprobamate   \n",
            "..            ...                    ...   \n",
            "137     175675139      Lysine Impurity 4   \n",
            "138     175675140      Lysine Impurity 5   \n",
            "139     175675141      Lysine Impurity 6   \n",
            "140     176479302    Aspirin Impurity 19   \n",
            "141     176479303    Aspirin Impurity 20   \n",
            "\n",
            "                                              Synonyms Molecular_Formula  \\\n",
            "0    4-HYDROXYBENZOIC ACID|99-96-7|p-Hydroxybenzoic...            C7H6O3   \n",
            "1    salicylic acid|2-Hydroxybenzoic acid|69-72-7|o...            C7H6O3   \n",
            "2    acetaminophen|Paracetamol|4-Acetamidophenol|10...           C8H9NO2   \n",
            "3    aspirin|ACETYLSALICYLIC ACID|50-78-2|2-Acetoxy...            C9H8O4   \n",
            "4    meprobamate|Equanil|Miltown|Meprospan|Tranmep|...         C9H18N2O4   \n",
            "..                                                 ...               ...   \n",
            "137  Lysine Impurity 4|Lysine Aspirin Impurity 12|(...        C15H20N2O5   \n",
            "138  Lysine Impurity 5|Lysine Aspirin Impurity 13|(...        C13H18N2O4   \n",
            "139  Lysine Impurity 6|Lysine Aspirin Impurity 14|(...        C15H20N2O5   \n",
            "140                                Aspirin Impurity 19          C13H14O9   \n",
            "141                                Aspirin Impurity 20          C13H14O9   \n",
            "\n",
            "                                                 InChI  \\\n",
            "0    InChI=1S/C7H6O3/c8-6-3-1-5(2-4-6)7(9)10/h1-4,8...   \n",
            "1    InChI=1S/C7H6O3/c8-6-4-2-1-3-5(6)7(9)10/h1-4,8...   \n",
            "2    InChI=1S/C8H9NO2/c1-6(10)9-7-2-4-8(11)5-3-7/h2...   \n",
            "3    InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)...   \n",
            "4    InChI=1S/C9H18N2O4/c1-3-4-9(2,5-14-7(10)12)6-1...   \n",
            "..                                                 ...   \n",
            "137  InChI=1S/C15H20N2O5/c1-10(18)16-9-5-4-7-12(15(...   \n",
            "138  InChI=1S/C13H18N2O4/c14-10(13(18)19)6-3-4-8-15...   \n",
            "139  InChI=1S/C15H20N2O5/c1-10(18)17-12(15(21)22)7-...   \n",
            "140  InChI=1S/C13H14O9/c14-6-4-2-1-3-5(6)12(20)22-1...   \n",
            "141  InChI=1S/C13H14O9/c14-7-8(15)10(12(19)20)22-13...   \n",
            "\n",
            "                                                SMILES  \\\n",
            "0                                 C1=CC(=CC=C1C(=O)O)O   \n",
            "1                               C1=CC=C(C(=C1)C(=O)O)O   \n",
            "2                                CC(=O)NC1=CC=C(C=C1)O   \n",
            "3                             CC(=O)OC1=CC=CC=C1C(=O)O   \n",
            "4                            CCCC(C)(COC(=O)N)COC(=O)N   \n",
            "..                                                 ...   \n",
            "137         CC(=O)NCCCC[C@H](C(=O)O)NC(=O)C1=CC=CC=C1O   \n",
            "138           C1=CC=C(C(=C1)C(=O)NCCCC[C@H](C(=O)O)N)O   \n",
            "139         CC(=O)N[C@H](CCCCNC(=O)C1=CC=CC=C1O)C(=O)O   \n",
            "140  C1=CC=C(C(=C1)C(=O)O[C@H]2C([C@H]([C@@H](C(O2)...   \n",
            "141  C1=CC=C(C(=C1)C(=O)O)O[C@H]2C([C@H]([C@@H](C(O...   \n",
            "\n",
            "                        InChIKey  \\\n",
            "0    FJKROLUGYXJWQN-UHFFFAOYSA-N   \n",
            "1    YGSDEFSMJLZEOE-UHFFFAOYSA-N   \n",
            "2    RZVAJINKPMORJF-UHFFFAOYSA-N   \n",
            "3    BSYNRYMUTXBXSQ-UHFFFAOYSA-N   \n",
            "4    NPPQSCRMBWNHMW-UHFFFAOYSA-N   \n",
            "..                           ...   \n",
            "137  IVPTVZPISGRIAZ-GFCCVEGCSA-N   \n",
            "138  UKMVTNVVYJLYJD-SNVBAGLBSA-N   \n",
            "139  QWMWCSINPFJDPH-GFCCVEGCSA-N   \n",
            "140  IXVVXKRKCLJCKA-HSLBDKFOSA-N   \n",
            "141  JSCWDKKMLIQCMR-QTQTTWAUSA-N   \n",
            "\n",
            "                                            IUPAC_Name  \\\n",
            "0                                4-hydroxybenzoic acid   \n",
            "1                                2-hydroxybenzoic acid   \n",
            "2                         N-(4-hydroxyphenyl)acetamide   \n",
            "3                              2-acetyloxybenzoic acid   \n",
            "4    [2-(carbamoyloxymethyl)-2-methylpentyl] carbamate   \n",
            "..                                                 ...   \n",
            "137  (2R)-6-acetamido-2-[(2-hydroxybenzoyl)amino]he...   \n",
            "138  (2R)-2-amino-6-[(2-hydroxybenzoyl)amino]hexano...   \n",
            "139  (2R)-2-acetamido-6-[(2-hydroxybenzoyl)amino]he...   \n",
            "140  (3S,4S,6S)-3,4,5-trihydroxy-6-(2-hydroxybenzoy...   \n",
            "141  (3S,4S,6S)-6-(2-carboxyphenoxy)-3,4,5-trihydro...   \n",
            "\n",
            "                         MeSH_Headings  \\\n",
            "0                4-hydroxybenzoic acid   \n",
            "1    Keralyt|compound W|Salicylic Acid   \n",
            "2                        Acetaminophen   \n",
            "3                              Aspirin   \n",
            "4                          Meprobamate   \n",
            "..                                 ...   \n",
            "137                                NaN   \n",
            "138                                NaN   \n",
            "139                                NaN   \n",
            "140                                NaN   \n",
            "141                                NaN   \n",
            "\n",
            "                                    Annotation_Content  ...  \\\n",
            "0    Agrochemical Information|Biological Test Resul...  ...   \n",
            "1    Biological Test Results|Interactions and Pathw...  ...   \n",
            "2    Agrochemical Information|Biological Test Resul...  ...   \n",
            "3    Biological Test Results|Interactions and Pathw...  ...   \n",
            "4    Biological Test Results|Interactions and Pathw...  ...   \n",
            "..                                                 ...  ...   \n",
            "137                                                NaN  ...   \n",
            "138                                                NaN  ...   \n",
            "139                                                NaN  ...   \n",
            "140                                                NaN  ...   \n",
            "141                                                NaN  ...   \n",
            "\n",
            "    Defined_Atom_Stereo_Count Undefined_Atom_Stereo_Count  \\\n",
            "0                           0                           0   \n",
            "1                           0                           0   \n",
            "2                           0                           0   \n",
            "3                           0                           0   \n",
            "4                           0                           0   \n",
            "..                        ...                         ...   \n",
            "137                         1                           0   \n",
            "138                         1                           0   \n",
            "139                         1                           0   \n",
            "140                         3                           2   \n",
            "141                         3                           2   \n",
            "\n",
            "    Total_Bond_Stereo_Count Defined_Bond_Stereo_Count  \\\n",
            "0                         0                         0   \n",
            "1                         0                         0   \n",
            "2                         0                         0   \n",
            "3                         0                         0   \n",
            "4                         0                         0   \n",
            "..                      ...                       ...   \n",
            "137                       0                         0   \n",
            "138                       0                         0   \n",
            "139                       0                         0   \n",
            "140                       0                         0   \n",
            "141                       0                         0   \n",
            "\n",
            "     Undefined_Bond_Stereo_Count  Linked_PubChem_Literature_Count  \\\n",
            "0                              0                             8688   \n",
            "1                              0                            42633   \n",
            "2                              0                            77591   \n",
            "3                              0                           139004   \n",
            "4                              0                             5582   \n",
            "..                           ...                              ...   \n",
            "137                            0                                0   \n",
            "138                            0                                0   \n",
            "139                            0                                0   \n",
            "140                            0                                0   \n",
            "141                            0                                0   \n",
            "\n",
            "     Linked_PubChem_Patent_Count  Linked_PubChem_Patent_Family_Count  \\\n",
            "0                          70981                               38516   \n",
            "1                         107612                               55645   \n",
            "2                          43313                               23183   \n",
            "3                         104275                               47162   \n",
            "4                          53133                               17667   \n",
            "..                           ...                                 ...   \n",
            "137                            0                                   0   \n",
            "138                            0                                   0   \n",
            "139                            0                                   0   \n",
            "140                            0                                   0   \n",
            "141                            0                                   0   \n",
            "\n",
            "     Annotation_Type_Count  Create_Date  \n",
            "0                       19     20040916  \n",
            "1                       19     20040916  \n",
            "2                       18     20040916  \n",
            "3                       18     20040916  \n",
            "4                       16     20050325  \n",
            "..                     ...          ...  \n",
            "137                      0     20250624  \n",
            "138                      0     20250624  \n",
            "139                      0     20250624  \n",
            "140                      0     20250812  \n",
            "141                      0     20250812  \n",
            "\n",
            "[142 rows x 38 columns]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "4QavTEV9_45j",
        "outputId": "11ca0631-2d5d-4ffc-f9ce-c66fdae4dfaf"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "mol_wt:  314.246\n",
            "LogP:  -1.3442000000000003\n",
            "H_Acceptors:  7\n",
            "H_Donors 5\n",
            "lipsinki rule: pass\n",
            "logP: pass\n",
            "H_Acceptors: pass\n",
            "H_Donors :pass\n",
            "\n",
            " checking Lipsinki rule.... \n",
            "\n",
            "lipsinki pass\n",
            "rot_bonds 4\n",
            "tpsa 153.75\n",
            "\n",
            " checking veber rule.... \n",
            "\n",
            " rot_bonds veber rule: pass\n",
            "tpsa veber rule :fail\n",
            "veber:fail\n"
          ]
        }
      ],
      "source": [
        "from rdkit import Chem\n",
        "from rdkit.Chem import Draw\n",
        "from rdkit.Chem import Descriptors\n",
        "import pandas as pd\n",
        "df=pd.read_csv(\"PubChem_compound_CID__ouUHalf9MkEFb7p2OA7zUWjn94dDA2X8H9l-sATIbLEE0VA.csv\")\n",
        "SmilesList=df[\"SMILES\"]\n",
        "results=[]\n",
        "for Smiles in SmilesList:\n",
        "    mol=Chem.MolFromSmiles(Smiles)\n",
        "if mol is None:\n",
        "    print(\"invalid smiles\")\n",
        "    exit()\n",
        "#<------- descriptors access------->\n",
        "mol_wt=Descriptors.MolWt(mol)\n",
        "logP=Descriptors.MolLogP(mol)\n",
        "H_Acceptors=Descriptors.NumHAcceptors(mol)\n",
        "H_Donors=Descriptors.NumHDonors(mol)\n",
        "#<-------print descriptors------->\n",
        "print(\"mol_wt: \",mol_wt)\n",
        "print(\"LogP: \",logP)\n",
        "print(\"H_Acceptors: \",H_Acceptors)\n",
        "print(\"H_Donors\",H_Donors)\n",
        "Lipsinki_fail= 0\n",
        "if(mol_wt<=500):\n",
        "    print(\"lipsinki rule: pass\")\n",
        "else:\n",
        "    print(\"mol_wt: fails\")\n",
        "    Lipsinki_fail+=1\n",
        "if(logP<=5):\n",
        "     print(\"logP: pass\")\n",
        "else:\n",
        "     print(\"logP: fails\")\n",
        "     Lipsinki_fail+=1\n",
        "if(H_Acceptors<=10):\n",
        "      print(\"H_Acceptors: pass\")\n",
        "else:\n",
        "      print(\"H_Acceptors:fails\")\n",
        "      Lipsinki_fail+=1\n",
        "if(H_Donors<=5):\n",
        "      print(\"H_Donors :pass\")\n",
        "else:\n",
        "      print(\"H_Donors: fails\")\n",
        "      Lipsinki_fail+=1\n",
        "\n",
        "print(\"\\n checking Lipsinki rule.... \\n\")\n",
        "if Lipsinki_fail<=1:\n",
        "      print(\"lipsinki pass\")\n",
        "else:\n",
        "      print(\"lipsinki fails\")\n",
        "\n",
        "#<-------VEBER RULE------->\n",
        "rot_bonds=Descriptors.NumRotatableBonds(mol)\n",
        "tpsa=Descriptors.TPSA(mol)\n",
        "\n",
        "#<-------print descriptors------->\n",
        "print(\"rot_bonds\",rot_bonds)\n",
        "print(\"tpsa\",tpsa)\n",
        "#<----checking veber rule is pass or not---->\n",
        "print(\"\\n checking veber rule.... \\n\")\n",
        "veber_fail=0\n",
        "if rot_bonds<=10:\n",
        "  print(\" rot_bonds veber rule: pass\")\n",
        "else:\n",
        "  print(\"rot_bonds veber rule :fail\")\n",
        "  veber_fail+=1\n",
        "if tpsa<=140:\n",
        "  print(\"tpsa veber rule: pass\")\n",
        "else:\n",
        "  print(\"tpsa veber rule :fail\")\n",
        "  veber_fail+=1\n",
        "if veber_fail==0:\n",
        "  print(\"veber: pass\")\n",
        "else:\n",
        "  print(\"veber:fail\")\n"
      ]
    }
  ]
}